### ISSUE TITLE
Plugin doesn't display data due to broken filtering (related to PHP7?)

### ISSUE THREAD

**Issue by tmo26** [Cyrille37/dokuwiki-plugin-datatemplate#6]
## Issue
No output at all from the datatemplate plugin if filter matches.
Plugin seems to work in general, since it displays "Nothing." when the filter is set to a non-existing model.
However, if the filter is set to an existing model, there is no output at all from the plugin.

## Symptoms
In the html of the example page:
If filter **doesn't** match: `<div class="templatelist">Nothing.</div>` -> Expected behaviour
If filter **does** match: `<div class="dttpllist"></div>` -> Unexpected behaviour, there is not content at all in the div.
(class="dttpllist" is expected, since it is set via `---- datatemplatelist dttpllist ----`)

This issue does not seem to be related to interference with other plugins (tested by deactivating all plugins).

## Dokuwiki configurations

**Working (OpenWrt wiki)**
2016-06-26a "Elenor of Tsort"
Template: custom
data plugin: 2016-03-11
datatemplate plugin: 2016-08-03
webserver: nginx/1.2.1
php_version: 5.4.45-0+deb7u5
working template: https://wiki.openwrt.org/meta/template_datatemplatelist
working example: https://wiki.openwrt.org/ru/toh/asus/asus_wl-330ge#hardware

**Working (private demowiki)**
2016-06-26a "Elenor of Tsort"
Template: bootstrap3
data plugin: 2016-03-11
datatemplate plugin: 2016-08-03
webserver: nginx/1.6.2
php_version: 5.6.29-0+deb8u1

**Not working (LEDE wiki)**
2016-06-26a "Elenor of Tsort"
Template: bootstrap3
data plugin: 2016-03-11
datatemplate plugin: 2016-08-03
webserver: nginx/1.10.1
php_version: 7.0.11-1~dotdeb+8.1
**non working example:** https://lede-project.org/playground/datatemplatelist
template used in this example: https://lede-project.org/templates/datatemplate_list2

**Comment by marcofenoglio** [comment]
Try to comment the line number 245 in syntax/list.php.
For me works great.

**Comment by tmo26** [comment]
Commenting line number 245 in syntax/list.php did the trick.
The datatemplate plugin is now working as expected (although I have to admit that I havn't tested it thoroughly yet).

**Comment by EdGrrr** [comment]
For other people with the same issue, note that to fix syntax/entry.php, you also need to comment out line 149 in that file (performs the same role for entries)
